### STAGE 1

# Extend image
FROM node as build

# Create app directory
WORKDIR /app

# Copy dependency list and install depz
COPY package.json .
RUN npm install

# Bundle app source
COPY . .

# Environment variables
# Use to create conditions
ENV NODE_ENV production

RUN npm run build

### STAGE 2

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html